title: Rhia Catapano
url: "https://rhiacatapano.com"
baseurl: "/"

markdown: kramdown

favicon: yes
favicon_location: rhia_favicon.ico

tracking_id: #

footer: yes
footer_url: "rhia.catapano@rotman.utoronto.ca"
footer_text: "Rhia Catapano, 2023"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Research"
   link: "https://discover.research.utoronto.ca/12137-rhia-catapano/publications"
 - name: "CV"
   link: "https://drive.google.com/file/d/1yjRG4Es4J1Li1KSRYiQdorUt9NB_Prqz/view"
