title: Rhia Catapano
url: "https://rhiacatapano.com"
baseurl: "/"

markdown: kramdown

favicon: yes
favicon_location: rhia_favicon.ico

tracking_id: #

footer: yes
footer_url: "rhiac@rotman.utoronto.ca"
footer_text: "Rhia Catapano, 2022"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Research"
   link: "research"
 - name: "CV"
   link: "https://drive.google.com/file/d/1R342TYWOdLh1kYu7NbNYEy6kXMFiPPgo/view"
